# Importing the necessary libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns 
import statistics
%matplotlib inline

from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler 
from sklearn.preprocessing import StandardScaler
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score, mean_squared_error
from sklearn.model_selection import train_test_split

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# Load Data

In [2]:
# Showing all the columns and rows. Normally pandas have a max limit.

In [3]:
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 100)

In [4]:
# Loading the raw data .csv files into the dataframes

# Decided to get both San Mateo County Airbnb data and Santa Clara County Airbnb Data
# will read these two datasets into my notebook, check their main features, 
# decide what columns might be relevant in the preliminary step of cleaning the data
# then will concat these two dataframes. After concat, I will keep specific locations 
# Specific locations will be: Redwood City, Menlo Park, Palo Alto, Mountain View, and Sunnyvale
# Stanford Palo Alto will be my main point and will check other cities' prices surrounding it

In [5]:
abnb_sm_df = pd.read_csv('San_Mateo_listings.csv')
abnb_sc_df = pd.read_csv('Santa_Clara_listings.csv')

# Discovery

In [6]:
# Looking at the dataframe main features (head, shape, info)

In [7]:
def df_main_features(df):
    display(df.shape)
    display(df.head())
    display(df.info())
    display(df.isnull().sum())
    display(df.describe())
    return

In [8]:
df_main_features(abnb_sm_df)

(3358, 74)

,id,listing_url,scrape_id,last_scraped,name,description,neighborhood_overview,picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,4952,https://www.airbnb.com/rooms/4952,20220615153426,2022-06-16,Butterfly Inn near Stanford with weekly cleaning,Small private room with lovely garden setting ...,"Located in Professorville, Palo Alto, one of t...",https://a0.muscache.com/pictures/529448/3d73e0...,7054,https://www.airbnb.com/users/show/7054,Mei Lin,2009-01-24,"Palo Alto, California, United States","I have lived and worked in Asia, Europe, Austr...",within an hour,100%,95%,t,https://a0.muscache.com/im/users/7054/profile_...,https://a0.muscache.com/im/users/7054/profile_...,Palo Alto,5,5,"['email', 'phone', 'work_email']",t,t,"Palo Alto, California, United States",Unincorporated Areas,NaN,37.43932,-122.15741,Private room,Private room,1,NaN,2 shared baths,1.0,1.0,"[""Freezer"", ""Lock on bedroom door"", ""Carbon mo...",$70.00,31,365,31,31,365,365,31.0,365.0,NaN,t,0,0,0,58,2022-06-16,76,1,0,2009-08-02,2022-04-02,4.79,4.81,4.88,4.86,4.83,4.89,4.78,NaN,f,5,0,5,0,0.48
1,21373,https://www.airbnb.com/rooms/21373,20220615153426,2022-06-16,Bonsai Garden near Stanford with weekly cleaning,Small bedroom and desk Lovely garden setting i...,This room is in an ultra convenient location i...,https://a0.muscache.com/pictures/527285/0f9d08...,7054,https://www.airbnb.com/users/show/7054,Mei Lin,2009-01-24,"Palo Alto, California, United States","I have lived and worked in Asia, Europe, Austr...",within an hour,100%,95%,t,https://a0.muscache.com/im/users/7054/profile_...,https://a0.muscache.com/im/users/7054/profile_...,Palo Alto,5,5,"['email', 'phone', 'work_email']",t,t,"Palo Alto, California, United States",Unincorporated Areas,NaN,37.43972,-122.15532,Private room,Private room,1,NaN,2 shared baths,1.0,1.0,"[""Freezer"", ""Lock on bedroom door"", ""Carbon mo...",$70.00,31,365,31,31,365,365,31.0,365.0,NaN,t,0,0,0,0,2022-06-16,264,1,0,2010-05-28,2022-05-15,4.87,4.82,4.79,4.85,4.90,4.96,4.74,NaN,f,5,0,5,0,1.80
2,26622,https://www.airbnb.com/rooms/26622,20220615153426,2022-06-15,Upstairs Bedroom-3 day minimum stay,Lovely bedroom and bathroom facilities in our ...,Daly City is as multi-cultural as you can get!...,https://a0.muscache.com/pictures/66176875/1ecd...,113123,https://www.airbnb.com/users/show/113123,Syd,2010-04-24,"Daly City, California, United States","I am a retired teacher (20 years First Grade, ...",within a few hours,100%,67%,f,https://a0.muscache.com/im/users/113123/profil...,https://a0.muscache.com/im/users/113123/profil...,Daly City,1,1,"['email', 'phone']",t,f,"Daly City, California, United States",Daly City,NaN,37.69490,-122.47517,Private room in home,Private room,2,NaN,1.5 shared baths,1.0,1.0,"[""Lock on bedroom door"", ""Carbon monoxide alar...",$150.00,3,7,3,3,7,7,3.0,7.0,NaN,t,21,47,77,352,2022-06-15,255,1,1,2010-07-02,2022-05-29,4.96,4.96,4.97,4.96,4.95,4.73,4.92,NaN,f,1,0,1,0,1.75
3,39342,https://www.airbnb.com/rooms/39342,20220615153426,2022-06-15,Dog friendly. Near the beach. Lovely Cottage.,31 NIGHT MINIMUM. Walk to Pacifica Beach from...,Quite neighborhood with easy walk to the beach.,https://a0.muscache.com/pictures/219887/f319d2...,127367,https://www.airbnb.com/users/show/127367,Michelle,2010-05-18,"Sonoma, California, United States",I manage 15 properties in San Francisco and P...,within an hour,100%,73%,f,https://a0.muscache.com/im/pictures/user/d08c9...,https://a0.muscache.com/im/pictures/user/d08c9...,Pacifica,28,28,"['email', 'phone']",t,t,"Pacifica, California, United States",Pacifica,NaN,37.62972,-122.48739,Entire home,Entire home/apt,3,NaN,1 bath,2.0,2.0,"[""Keypad"", ""Carbon monoxide alarm"", ""TV with s...",$138.00,31,365,31,31,365,365,31.0,365.0,NaN,t,0,0,0,260,2022-06-15,3,1,0,2010-08-22,2022-02-05,4.67,5.00,5.00,4.50,5.00,5.00,5.00,NaN,f,2,2,0,0,0.02
4,40560,https://www.airbnb.com/rooms/40560,20220615153426,2022-06-16,MOST COMFORTABLE BED EVER,"The ""Purple Room,"" as I call it, is great for ...",My neighborhood is lovely and a great place to...,https://a0.muscache.com/pictures/630306/19db9b...,174725,https://www.airbnb.com/users/show/174725,Megan,2010-07-20,"Palo Alto, California, United States","Mom, former journalist but now have several bu...",within an hour,100%,100%,t,https://a0.muscache.com/im/users/174725/profil...,https://a0.muscache.com/im/users/174725/profil...,Palo Alto,0,0,"['email', 'phone']",t,t,"Palo Alto, California, United States",Unincorporated Areas,NaN,37.45379,-122.13867,Private room in home,Private room,2,NaN,1 shared bath,1.0,1.0,"[""Backyard"", ""Carbon monoxide alarm"", ""TV with...",$115.00,2,100,2,2,100,100,2.0,100.0,NaN,t,0,0,0,255,2022-06-16,139,5,1,2010-09-18,2022-06-12,4.91,4.94,4.95,4.90,4.95,4.94,4.83,NaN,f,2,0,2,0,0.97

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3358 entries, 0 to 3357
Data columns (total 74 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            3358 non-null   int64
 1   listing_url                                   3358 non-null   object
 2   scrape_id                                     3358 non-null   int64
 3   last_scraped                                  3358 non-null   object
 4   name                                          3358 non-null   object
 5   description                                   3317 non-null   object
 6   neighborhood_overview                         2340 non-null   object
 7   picture_url                                   3358 non-null   object
 8   host_id                                       3358 non-null   int64
 9   host_url                                      3358 non-null   object
 10  host_name                                     3358 non-null   object
 11  host_since                                    3358 non-null   object
 12  host_location                                 3355 non-null   object
 13  host_about                                    2213 non-null   object
 14  host_response_time                            3025 non-null   object
 15  host_response_rate                            3025 non-null   object
 16  host_acceptance_rate                          3142 non-null   object
 17  host_is_superhost                             3358 non-null   object
 18  host_thumbnail_url                            3358 non-null   object
 19  host_picture_url                              3358 non-null   object
 20  host_neighbourhood                            2820 non-null   object
 21  host_listings_count                           3358 non-null   int64
 22  host_total_listings_count                     3358 non-null   int64
 23  host_verifications                            3358 non-null   object
 24  host_has_profile_pic                          3358 non-null   object
 25  host_identity_verified                        3358 non-null   object
 26  neighbourhood                                 2340 non-null   object
 27  neighbourhood_cleansed                        3358 non-null   object
 28  neighbourhood_group_cleansed                  0 non-null      float64
 29  latitude                                      3358 non-null   float64
 30  longitude                                     3358 non-null   float64
 31  property_type                                 3358 non-null   object
 32  room_type                                     3358 non-null   object
 33  accommodates                                  3358 non-null   int64
 34  bathrooms                                     0 non-null      float64
 35  bathrooms_text                                3353 non-null   object
 36  bedrooms                                      3135 non-null   float64
 37  beds                                          3304 non-null   float64
 38  amenities                                     3358 non-null   object
 39  price                                         3358 non-null   object
 40  minimum_nights                                3358 non-null   int64
 41  maximum_nights                                3358 non-null   int64
 42  minimum_minimum_nights                        3358 non-null   int64
 43  maximum_minimum_nights                        3358 non-null   int64
 44  minimum_maximum_nights                        3358 non-null   int64
 45  maximum_maximum_nights                        3358 non-null   int64
 46  minimum_nights_avg_ntm                        3358 non-null   float64
 47  maximum_nights_avg_ntm                        3358 non-null   float64
 48  calendar_updated                              0 non-null      float64
 49  has_availability                              3358 non-null   object
 50  availability_30                               3358 non-null   int64
 51  availability_60                               3358 non-null   int64
 52  availability_90                               3358 non-null   int64
 53  availability_365                              3358 non-null   int64
 54  calendar_last_scraped                         3358 non-null   object
 55  number_of_reviews                             3358 non-null   int64
 56  number_of_reviews_ltm                         3358 non-null   int64
 57  number_of_reviews_l30d                        3358 non-null   int64
 58  first_review                                  2855 non-null   object
 59  last_review                                   2855 non-null   object
 60  review_scores_rating                          2855 non-null   float64
 61  review_scores_accuracy                        2849 non-null   float64
 62  review_scores_cleanliness                     2849 non-null   float64
 63  review_scores_checkin                         2849 non-null   float64
 64  review_scores_communication                   2849 non-null   float64
 65  review_scores_location                        2849 non-null   float64
 66  review_scores_value                           2849 non-null   float64
 67  license                                       260 non-null    object
 68  instant_bookable                              3358 non-null   object
 69  calculated_host_listings_count                3358 non-null   int64
 70  calculated_host_listings_count_entire_homes   3358 non-null   int64
 71  calculated_host_listings_count_private_rooms  3358 non-null   int64
 72  calculated_host_listings_count_shared_rooms   3358 non-null   int64
 73  reviews_per_month                             2855 non-null   float64
dtypes: float64(17), int64(23), object(34)
memory usage: 1.9+ MB

None

id                                                 0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
name                                               0
description                                       41
neighborhood_overview                           1018
picture_url                                        0
host_id                                            0
host_url                                           0
host_name                                          0
host_since                                         0
host_location                                      3
host_about                                      1145
host_response_time                               333
host_response_rate                               333
host_acceptance_rate                             216
host_is_superhost                                  0
host_thumbnail_url                                 0
host_picture_url                                   0
host_neighbourhood                               538
host_listings_count                                0
host_total_listings_count                          0
host_verifications                                 0
host_has_profile_pic                               0
host_identity_verified                             0
neighbourhood                                   1018
neighbourhood_cleansed                             0
neighbourhood_group_cleansed                    3358
latitude                                           0
longitude                                          0
property_type                                      0
room_type                                          0
accommodates                                       0
bathrooms                                       3358
bathrooms_text                                     5
bedrooms                                         223
beds                                              54
amenities                                          0
price                                              0
minimum_nights                                     0
maximum_nights                                     0
minimum_minimum_nights                             0
maximum_minimum_nights                             0
minimum_maximum_nights                             0
maximum_maximum_nights                             0
minimum_nights_avg_ntm                             0
maximum_nights_avg_ntm                             0
calendar_updated                                3358
has_availability                                   0
availability_30                                    0
availability_60                                    0
availability_90                                    0
availability_365                                   0
calendar_last_scraped                              0
number_of_reviews                                  0
number_of_reviews_ltm                              0
number_of_reviews_l30d                             0
first_review                                     503
last_review                                      503
review_scores_rating                             503
review_scores_accuracy                           509
review_scores_cleanliness                        509
review_scores_checkin                            509
review_scores_communication                      509
review_scores_location                           509
review_scores_value                              509
license                                         3098
instant_bookable                                   0
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                                503
dtype: int64

,id,scrape_id,host_id,host_listings_count,host_total_listings_count,neighbourhood_group_cleansed,latitude,longitude,accommodates,bathrooms,bedrooms,beds,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,availability_30,availability_60,availability_90,availability_365,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
count,3.358000e+03,3.358000e+03,3.358000e+03,3358.000000,3358.000000,0.0,3358.000000,3358.000000,3358.000000,0.0,3135.000000,3304.000000,3358.000000,3358.000000,3358.000000,3358.000000,3.358000e+03,3.358000e+03,3358.000000,3.358000e+03,0.0,3358.000000,3358.000000,3358.000000,3358.000000,3358.000000,3358.000000,3358.000000,2855.000000,2849.000000,2849.000000,2849.000000,2849.000000,2849.000000,2849.000000,3358.000000,3358.000000,3358.000000,3358.000000,2855.000000
mean,7.216392e+16,2.022062e+13,1.134449e+08,225.823407,225.823407,NaN,37.561683,-122.330873,3.848124,NaN,1.790112,2.252724,11.314175,600.114056,18.972901,44.058666,2.558844e+06,2.558877e+06,42.528529,2.558868e+06,NaN,6.582490,17.504467,35.463669,177.131030,54.636391,14.034544,1.348719,4.766483,4.830702,4.785869,4.890530,4.865721,4.801232,4.716164,13.334127,11.608100,1.482132,0.243597,1.857349
std,1.954779e+17,1.468969e+00,1.253650e+08,754.245304,754.245304,NaN,0.103341,0.122456,2.965322,NaN,1.175409,1.923607,22.333177,528.322304,82.565096,151.278875,7.408413e+07,7.408413e+07,148.070209,7.408413e+07,NaN,8.640447,18.659128,27.843123,122.760363,86.047498,20.899536,2.159326,0.426797,0.318881,0.369339,0.290838,0.334824,0.308900,0.359869,33.385862,33.626443,3.492638,2.108802,1.892206
min,4.952000e+03,2.022062e+13,7.054000e+03,0.000000,0.000000,NaN,37.137190,-122.519040,0.000000,NaN,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000e+00,1.000000e+00,1.000000,1.000000e+00,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.010000
25%,2.098340e+07,2.022062e+13,1.590209e+07,1.000000,1.000000,NaN,37.468257,-122.445817,2.000000,NaN,1.000000,1.000000,1.000000,45.000000,1.000000,2.000000,3.600000e+02,3.650000e+02,1.800000,3.650000e+02,NaN,0.000000,0.000000,10.000000,65.000000,2.000000,0.000000,0.000000,4.710000,4.790000,4.730000,4.890000,4.860000,4.740000,4.640000,1.000000,0.000000,0.000000,0.000000,0.420000
50%,3.755862e+07,2.022062e+13,5.771725e+07,2.000000,2.000000,NaN,37.549075,-122.336850,3.000000,NaN,1.000000,2.000000,2.000000,365.000000,2.000000,3.000000,1.125000e+03,1.125000e+03,3.000000,1.125000e+03,NaN,2.000000,12.000000,32.000000,167.000000,19.000000,4.000000,0.000000,4.880000,4.920000,4.900000,4.970000,4.960000,4.880000,4.800000,2.000000,1.000000,0.000000,0.000000,1.230000
75%,5.113984e+07,2.022062e+13,1.747920e+08,9.000000,9.000000,NaN,37.658358,-122.219080,5.000000,NaN,2.000000,3.000000,20.000000,1125.000000,14.000000,28.000000,1.125000e+03,1.125000e+03,21.000000,1.125000e+03,NaN,11.000000,30.000000,58.000000,301.000000,70.000000,20.000000,2.000000,4.980000,5.000000,5.000000,5.000000,5.000000,5.000000,4.910000,6.000000,3.000000,2.000000,0.000000,2.690000
max,6.491004e+17,2.022062e+13,4.633031e+08,3322.000000,3322.000000,NaN,37.728360,-122.111290,16.000000,NaN,8.000000,27.000000,365.000000,10000.000000,730.000000,730.000000,2.147484e+09,2.147484e+09,730.000000,2.147484e+09,NaN,30.000000,60.000000,90.000000,365.000000,885.000000,187.000000,22.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,152.000000,152.000000,27.000000,24.000000,17.740000

In [9]:
df_main_features(abnb_sc_df)

(5729, 74)

,id,listing_url,scrape_id,last_scraped,name,description,neighborhood_overview,picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,649100413671762836,https://www.airbnb.com/rooms/649100413671762836,20220615153449,2022-06-16,Cozy&Cheerful Luxuery bay trail house,"Kick back and relax in this calm, stylish space.",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,81523960,https://www.airbnb.com/users/show/81523960,Monica,2016-07-03,"Palo Alto, California, United States",NaN,NaN,NaN,NaN,f,https://a0.muscache.com/im/pictures/user/c5f67...,https://a0.muscache.com/im/pictures/user/c5f67...,NaN,1,1,"['email', 'phone']",t,t,NaN,Palo Alto,NaN,37.46911,-122.13203,Shared room in home,Shared room,2,NaN,1 shared bath,1.0,2.0,"[""Outdoor dining area"", ""Long term stays allow...",$85.00,1,365,1,1,365,365,1.0,365.0,NaN,t,0,0,10,284,2022-06-16,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,3,2,0,1,NaN
1,34284906,https://www.airbnb.com/rooms/34284906,20220615153449,2022-06-15,Skyline and Heaven Guesthouse,NaN,NaN,https://a0.muscache.com/pictures/23470d5b-5ba4...,7043660,https://www.airbnb.com/users/show/7043660,Rebecca,2013-06-21,"Woodside, California, United States",we are home designers and developers from the ...,NaN,NaN,NaN,f,https://a0.muscache.com/im/pictures/user/cdbb4...,https://a0.muscache.com/im/pictures/user/cdbb4...,NaN,1,1,"['email', 'phone']",t,t,NaN,Unincorporated Areas,NaN,37.32758,-122.20766,Entire guesthouse,Entire home/apt,2,NaN,1 bath,1.0,NaN,"[""Essentials"", ""Free parking on premises"", ""Pr...",$299.00,3,1125,3,3,1125,1125,3.0,1125.0,NaN,t,23,53,83,83,2022-06-15,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
2,48658485,https://www.airbnb.com/rooms/48658485,20220615153449,2022-06-15,"Modern 1 Bed/1 Bath with prvt entry, prvt patio",Introducing beautiful newly-constructed privat...,NaN,https://a0.muscache.com/pictures/b8998210-4075...,26479513,https://www.airbnb.com/users/show/26479513,Ashish,2015-01-21,"Fremont, California, United States",NaN,within an hour,100%,100%,t,https://a0.muscache.com/im/pictures/user/6994a...,https://a0.muscache.com/im/pictures/user/6994a...,Warm Springs,5,5,"['email', 'phone']",t,t,NaN,Milpitas,NaN,37.47384,-121.91877,Private room in home,Private room,2,NaN,1 private bath,1.0,1.0,"[""Essentials"", ""Air conditioning"", ""Long term ...",$72.00,1,1125,1,1,1125,1125,1.0,1125.0,NaN,t,4,30,60,60,2022-06-15,48,36,3,2021-03-18,2022-06-06,4.83,4.92,4.75,4.92,5.00,4.92,4.79,NaN,t,5,1,4,0,3.16
3,22251361,https://www.airbnb.com/rooms/22251361,20220615153449,2022-06-15,Remote Mountain Suite with Hot Tub,One-bedroom attached in-law suite with private...,Rural Mountain residential setting in the redw...,https://a0.muscache.com/pictures/20c61acb-d609...,50031570,https://www.airbnb.com/users/show/50031570,Emily,2015-11-28,"Los Gatos, California, United States","Attorney, outdoor enthusiast, Park City Utah n...",within an hour,100%,97%,t,https://a0.muscache.com/im/pictures/user/415c5...,https://a0.muscache.com/im/pictures/user/415c5...,NaN,1,1,"['email', 'phone', 'work_email']",t,t,"Los Gatos, California, United States",Unincorporated Areas,NaN,37.12520,-121.98971,Entire guest suite,Entire home/apt,3,NaN,1 bath,1.0,1.0,"[""Essentials"", ""Clothing storage: dresser and ...",$130.00,2,28,2,3,1125,1125,2.3,1125.0,NaN,t,0,0,12,75,2022-06-15,193,52,6,2018-02-26,2022-06-13,4.94,4.93,4.88,4.99,4.94,4.89,4.92,NaN,f,1,1,0,0,3.69
4,20761499,https://www.airbnb.com/rooms/20761499,20220615153449,2022-06-15,Lovely Private Room in Menlo Park near Stanford U,Lovely private room in a beautiful 3 bedroom ...,One of the best neighborhoods in the Bay Area....,https://a0.muscache.com/pictures/miso/Hosting-...,77312665,https://www.airbnb.com/users/show/77312665,Karn,2016-06-12,"West Menlo Park, California, United States",I was born in Delhi and came to the bay area ...,within an hour,100%,86%,f,https://a0.muscache.com/im/pictures/user/badff...,https://a0.muscache.com/im/pictures/user/badff...,Menlo Park,1,1,"['email', 'phone']",t,t,"Menlo Park, California, United States",Unincorporated Areas,NaN,37.42539,-122.20023,Private room in rental unit,Private room,1,NaN,1 shared bath,1.0,1.0,"[""Essentials"", ""Air conditioning"", ""Long term ...",$99.00,1,1125,1,1,1125,1125,1.0,1125.0,NaN,t,0,1,2,92,2022-06-15,8,5,0,2017-09-14,2022-03-31,4.88,4.88,4.38,5.00,5.00,4.75,5.00,NaN,f,2,0,2,0,0.14

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5729 entries, 0 to 5728
Data columns (total 74 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            5729 non-null   int64
 1   listing_url                                   5729 non-null   object
 2   scrape_id                                     5729 non-null   int64
 3   last_scraped                                  5729 non-null   object
 4   name                                          5728 non-null   object
 5   description                                   5609 non-null   object
 6   neighborhood_overview                         3479 non-null   object
 7   picture_url                                   5729 non-null   object
 8   host_id                                       5729 non-null   int64
 9   host_url                                      5729 non-null   object
 10  host_name                                     5729 non-null   object
 11  host_since                                    5729 non-null   object
 12  host_location                                 5717 non-null   object
 13  host_about                                    3820 non-null   object
 14  host_response_time                            5051 non-null   object
 15  host_response_rate                            5051 non-null   object
 16  host_acceptance_rate                          5268 non-null   object
 17  host_is_superhost                             5729 non-null   object
 18  host_thumbnail_url                            5729 non-null   object
 19  host_picture_url                              5729 non-null   object
 20  host_neighbourhood                            4827 non-null   object
 21  host_listings_count                           5729 non-null   int64
 22  host_total_listings_count                     5729 non-null   int64
 23  host_verifications                            5729 non-null   object
 24  host_has_profile_pic                          5729 non-null   object
 25  host_identity_verified                        5729 non-null   object
 26  neighbourhood                                 3479 non-null   object
 27  neighbourhood_cleansed                        5729 non-null   object
 28  neighbourhood_group_cleansed                  0 non-null      float64
 29  latitude                                      5729 non-null   float64
 30  longitude                                     5729 non-null   float64
 31  property_type                                 5729 non-null   object
 32  room_type                                     5729 non-null   object
 33  accommodates                                  5729 non-null   int64
 34  bathrooms                                     0 non-null      float64
 35  bathrooms_text                                5723 non-null   object
 36  bedrooms                                      5347 non-null   float64
 37  beds                                          5620 non-null   float64
 38  amenities                                     5729 non-null   object
 39  price                                         5729 non-null   object
 40  minimum_nights                                5729 non-null   int64
 41  maximum_nights                                5729 non-null   int64
 42  minimum_minimum_nights                        5729 non-null   int64
 43  maximum_minimum_nights                        5729 non-null   int64
 44  minimum_maximum_nights                        5729 non-null   int64
 45  maximum_maximum_nights                        5729 non-null   int64
 46  minimum_nights_avg_ntm                        5729 non-null   float64
 47  maximum_nights_avg_ntm                        5729 non-null   float64
 48  calendar_updated                              0 non-null      float64
 49  has_availability                              5729 non-null   object
 50  availability_30                               5729 non-null   int64
 51  availability_60                               5729 non-null   int64
 52  availability_90                               5729 non-null   int64
 53  availability_365                              5729 non-null   int64
 54  calendar_last_scraped                         5729 non-null   object
 55  number_of_reviews                             5729 non-null   int64
 56  number_of_reviews_ltm                         5729 non-null   int64
 57  number_of_reviews_l30d                        5729 non-null   int64
 58  first_review                                  4606 non-null   object
 59  last_review                                   4606 non-null   object
 60  review_scores_rating                          4606 non-null   float64
 61  review_scores_accuracy                        4585 non-null   float64
 62  review_scores_cleanliness                     4585 non-null   float64
 63  review_scores_checkin                         4585 non-null   float64
 64  review_scores_communication                   4585 non-null   float64
 65  review_scores_location                        4585 non-null   float64
 66  review_scores_value                           4585 non-null   float64
 67  license                                       55 non-null     object
 68  instant_bookable                              5729 non-null   object
 69  calculated_host_listings_count                5729 non-null   int64
 70  calculated_host_listings_count_entire_homes   5729 non-null   int64
 71  calculated_host_listings_count_private_rooms  5729 non-null   int64
 72  calculated_host_listings_count_shared_rooms   5729 non-null   int64
 73  reviews_per_month                             4606 non-null   float64
dtypes: float64(17), int64(23), object(34)
memory usage: 3.2+ MB

None

id                                                 0
listing_url                                        0
scrape_id                                          0
last_scraped                                       0
name                                               1
description                                      120
neighborhood_overview                           2250
picture_url                                        0
host_id                                            0
host_url                                           0
host_name                                          0
host_since                                         0
host_location                                     12
host_about                                      1909
host_response_time                               678
host_response_rate                               678
host_acceptance_rate                             461
host_is_superhost                                  0
host_thumbnail_url                                 0
host_picture_url                                   0
host_neighbourhood                               902
host_listings_count                                0
host_total_listings_count                          0
host_verifications                                 0
host_has_profile_pic                               0
host_identity_verified                             0
neighbourhood                                   2250
neighbourhood_cleansed                             0
neighbourhood_group_cleansed                    5729
latitude                                           0
longitude                                          0
property_type                                      0
room_type                                          0
accommodates                                       0
bathrooms                                       5729
bathrooms_text                                     6
bedrooms                                         382
beds                                             109
amenities                                          0
price                                              0
minimum_nights                                     0
maximum_nights                                     0
minimum_minimum_nights                             0
maximum_minimum_nights                             0
minimum_maximum_nights                             0
maximum_maximum_nights                             0
minimum_nights_avg_ntm                             0
maximum_nights_avg_ntm                             0
calendar_updated                                5729
has_availability                                   0
availability_30                                    0
availability_60                                    0
availability_90                                    0
availability_365                                   0
calendar_last_scraped                              0
number_of_reviews                                  0
number_of_reviews_ltm                              0
number_of_reviews_l30d                             0
first_review                                    1123
last_review                                     1123
review_scores_rating                            1123
review_scores_accuracy                          1144
review_scores_cleanliness                       1144
review_scores_checkin                           1144
review_scores_communication                     1144
review_scores_location                          1144
review_scores_value                             1144
license                                         5674
instant_bookable                                   0
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               1123
dtype: int64

,id,scrape_id,host_id,host_listings_count,host_total_listings_count,neighbourhood_group_cleansed,latitude,longitude,accommodates,bathrooms,bedrooms,beds,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,availability_30,availability_60,availability_90,availability_365,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
count,5.729000e+03,5.729000e+03,5.729000e+03,5729.000000,5729.000000,0.0,5729.000000,5729.000000,5729.000000,0.0,5347.000000,5620.000000,5729.000000,5729.000000,5729.000000,5729.000000,5.729000e+03,5.729000e+03,5729.000000,5.729000e+03,0.0,5729.000000,5729.000000,5729.000000,5729.000000,5729.000000,5729.000000,5729.000000,4606.000000,4585.000000,4585.000000,4585.000000,4585.000000,4585.000000,4585.000000,5729.000000,5729.00000,5729.000000,5729.000000,4606.000000
mean,8.188610e+16,2.022062e+13,1.233078e+08,301.879909,301.879909,NaN,37.351373,-121.974697,3.290103,NaN,1.619600,1.931317,13.176121,641.914645,20.813056,57.829290,4.873817e+06,6.748048e+06,56.081533,6.071292e+06,NaN,5.618782,15.149590,32.486821,178.089544,34.460290,8.775004,0.888288,4.723139,4.798009,4.735138,4.866041,4.830600,4.816840,4.690475,43.757898,41.37092,2.105429,0.281375,1.336198
std,2.064451e+17,2.101746e+00,1.257586e+08,848.718328,848.718328,NaN,0.073936,0.118236,2.418787,NaN,1.037482,1.502533,26.861549,494.059806,82.061918,176.343664,1.021896e+08,1.201935e+08,172.044535,1.103574e+08,NaN,8.726939,18.951832,28.325883,127.925597,63.562509,15.895219,1.715670,0.544540,0.390754,0.450958,0.352986,0.413634,0.347211,0.455451,105.200388,105.82580,6.217265,1.888957,1.566881
min,4.952000e+03,2.022062e+13,7.054000e+03,0.000000,0.000000,NaN,36.965600,-122.214140,0.000000,NaN,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000e+00,1.000000e+00,1.000000,1.000000e+00,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.00000,0.000000,0.000000,0.010000
25%,2.188225e+07,2.022062e+13,2.470909e+07,1.000000,1.000000,NaN,37.319546,-122.070110,2.000000,NaN,1.000000,1.000000,1.000000,90.000000,1.000000,2.000000,3.650000e+02,3.650000e+02,2.000000,3.650000e+02,NaN,0.000000,0.000000,4.000000,54.000000,1.000000,0.000000,0.000000,4.680000,4.770000,4.670000,4.880000,4.850000,4.790000,4.630000,1.000000,0.00000,0.000000,0.000000,0.290000
50%,3.977334e+07,2.022062e+13,7.174905e+07,3.000000,3.000000,NaN,37.355380,-121.962340,2.000000,NaN,1.000000,1.000000,3.000000,765.000000,3.000000,3.000000,1.125000e+03,1.125000e+03,3.000000,1.125000e+03,NaN,0.000000,6.000000,28.000000,167.000000,9.000000,2.000000,0.000000,4.870000,4.920000,4.880000,4.970000,4.960000,4.920000,4.800000,3.000000,1.00000,0.000000,0.000000,0.810000
75%,5.151011e+07,2.022062e+13,1.912639e+08,16.000000,16.000000,NaN,37.399790,-121.890230,4.000000,NaN,2.000000,2.000000,30.000000,1125.000000,28.000000,30.000000,1.125000e+03,1.125000e+03,29.500000,1.125000e+03,NaN,9.000000,27.000000,54.000000,303.000000,39.000000,10.000000,1.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,4.940000,11.000000,6.00000,2.000000,0.000000,1.880000
max,6.494853e+17,2.022062e+13,4.633031e+08,3322.000000,3322.000000,NaN,37.480080,-121.380120,16.000000,NaN,9.000000,20.000000,600.000000,1125.000000,730.000000,730.000000,2.147484e+09,2.147484e+09,730.000000,2.147484e+09,NaN,30.000000,60.000000,90.000000,365.000000,760.000000,206.000000,23.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,362.000000,362.00000,52.000000,15.000000,19.080000

In [10]:
abnb_sm_df.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'name', 'description',
       'neighborhood_overview', 'picture_url', 'host_id', 'host_url',
       'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

In [11]:
abnb_sm_df = abnb_sm_df[['id', 'host_since', 'host_is_superhost',  'neighbourhood', 'neighbourhood_cleansed', 'latitude','longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms', 'bedrooms', 'beds', 'price','minimum_nights', 'maximum_nights', 'calendar_last_scraped', 'number_of_reviews', 'first_review', 'last_review', 'review_scores_rating', 'review_scores_accuracy','review_scores_cleanliness','review_scores_communication', 'review_scores_location','review_scores_value', 'reviews_per_month']]

abnb_sc_df = abnb_sc_df[['id', 'host_since', 'host_is_superhost',  'neighbourhood', 'neighbourhood_cleansed', 'latitude','longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms', 'bedrooms', 'beds', 'price','minimum_nights', 'maximum_nights', 'calendar_last_scraped', 'number_of_reviews', 'first_review', 'last_review', 'review_scores_rating', 'review_scores_accuracy','review_scores_cleanliness','review_scores_communication', 'review_scores_location','review_scores_value', 'reviews_per_month']]

In [12]:
df_main_features(abnb_sm_df)

(3358, 27)

,id,host_since,host_is_superhost,neighbourhood,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bedrooms,beds,price,minimum_nights,maximum_nights,calendar_last_scraped,number_of_reviews,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month
0,4952,2009-01-24,t,"Palo Alto, California, United States",Unincorporated Areas,37.43932,-122.15741,Private room,Private room,1,NaN,1.0,1.0,$70.00,31,365,2022-06-16,76,2009-08-02,2022-04-02,4.79,4.81,4.88,4.83,4.89,4.78,0.48
1,21373,2009-01-24,t,"Palo Alto, California, United States",Unincorporated Areas,37.43972,-122.15532,Private room,Private room,1,NaN,1.0,1.0,$70.00,31,365,2022-06-16,264,2010-05-28,2022-05-15,4.87,4.82,4.79,4.90,4.96,4.74,1.80
2,26622,2010-04-24,f,"Daly City, California, United States",Daly City,37.69490,-122.47517,Private room in home,Private room,2,NaN,1.0,1.0,$150.00,3,7,2022-06-15,255,2010-07-02,2022-05-29,4.96,4.96,4.97,4.95,4.73,4.92,1.75
3,39342,2010-05-18,f,"Pacifica, California, United States",Pacifica,37.62972,-122.48739,Entire home,Entire home/apt,3,NaN,2.0,2.0,$138.00,31,365,2022-06-15,3,2010-08-22,2022-02-05,4.67,5.00,5.00,5.00,5.00,5.00,0.02
4,40560,2010-07-20,t,"Palo Alto, California, United States",Unincorporated Areas,37.45379,-122.13867,Private room in home,Private room,2,NaN,1.0,1.0,$115.00,2,100,2022-06-16,139,2010-09-18,2022-06-12,4.91,4.94,4.95,4.95,4.94,4.83,0.97

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3358 entries, 0 to 3357
Data columns (total 27 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           3358 non-null   int64
 1   host_since                   3358 non-null   object
 2   host_is_superhost            3358 non-null   object
 3   neighbourhood                2340 non-null   object
 4   neighbourhood_cleansed       3358 non-null   object
 5   latitude                     3358 non-null   float64
 6   longitude                    3358 non-null   float64
 7   property_type                3358 non-null   object
 8   room_type                    3358 non-null   object
 9   accommodates                 3358 non-null   int64
 10  bathrooms                    0 non-null      float64
 11  bedrooms                     3135 non-null   float64
 12  beds                         3304 non-null   float64
 13  price                        3358 non-null   object
 14  minimum_nights               3358 non-null   int64
 15  maximum_nights               3358 non-null   int64
 16  calendar_last_scraped        3358 non-null   object
 17  number_of_reviews            3358 non-null   int64
 18  first_review                 2855 non-null   object
 19  last_review                  2855 non-null   object
 20  review_scores_rating         2855 non-null   float64
 21  review_scores_accuracy       2849 non-null   float64
 22  review_scores_cleanliness    2849 non-null   float64
 23  review_scores_communication  2849 non-null   float64
 24  review_scores_location       2849 non-null   float64
 25  review_scores_value          2849 non-null   float64
 26  reviews_per_month            2855 non-null   float64
dtypes: float64(12), int64(5), object(10)
memory usage: 708.5+ KB

None

id                                0
host_since                        0
host_is_superhost                 0
neighbourhood                  1018
neighbourhood_cleansed            0
latitude                          0
longitude                         0
property_type                     0
room_type                         0
accommodates                      0
bathrooms                      3358
bedrooms                        223
beds                             54
price                             0
minimum_nights                    0
maximum_nights                    0
calendar_last_scraped             0
number_of_reviews                 0
first_review                    503
last_review                     503
review_scores_rating            503
review_scores_accuracy          509
review_scores_cleanliness       509
review_scores_communication     509
review_scores_location          509
review_scores_value             509
reviews_per_month               503
dtype: int64

,id,latitude,longitude,accommodates,bathrooms,bedrooms,beds,minimum_nights,maximum_nights,number_of_reviews,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month
count,3.358000e+03,3358.000000,3358.000000,3358.000000,0.0,3135.000000,3304.000000,3358.000000,3358.000000,3358.000000,2855.000000,2849.000000,2849.000000,2849.000000,2849.000000,2849.000000,2855.000000
mean,7.216392e+16,37.561683,-122.330873,3.848124,NaN,1.790112,2.252724,11.314175,600.114056,54.636391,4.766483,4.830702,4.785869,4.865721,4.801232,4.716164,1.857349
std,1.954779e+17,0.103341,0.122456,2.965322,NaN,1.175409,1.923607,22.333177,528.322304,86.047498,0.426797,0.318881,0.369339,0.334824,0.308900,0.359869,1.892206
min,4.952000e+03,37.137190,-122.519040,0.000000,NaN,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.010000
25%,2.098340e+07,37.468257,-122.445817,2.000000,NaN,1.000000,1.000000,1.000000,45.000000,2.000000,4.710000,4.790000,4.730000,4.860000,4.740000,4.640000,0.420000
50%,3.755862e+07,37.549075,-122.336850,3.000000,NaN,1.000000,2.000000,2.000000,365.000000,19.000000,4.880000,4.920000,4.900000,4.960000,4.880000,4.800000,1.230000
75%,5.113984e+07,37.658358,-122.219080,5.000000,NaN,2.000000,3.000000,20.000000,1125.000000,70.000000,4.980000,5.000000,5.000000,5.000000,5.000000,4.910000,2.690000
max,6.491004e+17,37.728360,-122.111290,16.000000,NaN,8.000000,27.000000,365.000000,10000.000000,885.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,17.740000

In [13]:
df_main_features(abnb_sc_df)

(5729, 27)

,id,host_since,host_is_superhost,neighbourhood,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bedrooms,beds,price,minimum_nights,maximum_nights,calendar_last_scraped,number_of_reviews,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month
0,649100413671762836,2016-07-03,f,NaN,Palo Alto,37.46911,-122.13203,Shared room in home,Shared room,2,NaN,1.0,2.0,$85.00,1,365,2022-06-16,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,34284906,2013-06-21,f,NaN,Unincorporated Areas,37.32758,-122.20766,Entire guesthouse,Entire home/apt,2,NaN,1.0,NaN,$299.00,3,1125,2022-06-15,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,48658485,2015-01-21,t,NaN,Milpitas,37.47384,-121.91877,Private room in home,Private room,2,NaN,1.0,1.0,$72.00,1,1125,2022-06-15,48,2021-03-18,2022-06-06,4.83,4.92,4.75,5.00,4.92,4.79,3.16
3,22251361,2015-11-28,t,"Los Gatos, California, United States",Unincorporated Areas,37.12520,-121.98971,Entire guest suite,Entire home/apt,3,NaN,1.0,1.0,$130.00,2,28,2022-06-15,193,2018-02-26,2022-06-13,4.94,4.93,4.88,4.94,4.89,4.92,3.69
4,20761499,2016-06-12,f,"Menlo Park, California, United States",Unincorporated Areas,37.42539,-122.20023,Private room in rental unit,Private room,1,NaN,1.0,1.0,$99.00,1,1125,2022-06-15,8,2017-09-14,2022-03-31,4.88,4.88,4.38,5.00,4.75,5.00,0.14

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5729 entries, 0 to 5728
Data columns (total 27 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           5729 non-null   int64
 1   host_since                   5729 non-null   object
 2   host_is_superhost            5729 non-null   object
 3   neighbourhood                3479 non-null   object
 4   neighbourhood_cleansed       5729 non-null   object
 5   latitude                     5729 non-null   float64
 6   longitude                    5729 non-null   float64
 7   property_type                5729 non-null   object
 8   room_type                    5729 non-null   object
 9   accommodates                 5729 non-null   int64
 10  bathrooms                    0 non-null      float64
 11  bedrooms                     5347 non-null   float64
 12  beds                         5620 non-null   float64
 13  price                        5729 non-null   object
 14  minimum_nights               5729 non-null   int64
 15  maximum_nights               5729 non-null   int64
 16  calendar_last_scraped        5729 non-null   object
 17  number_of_reviews            5729 non-null   int64
 18  first_review                 4606 non-null   object
 19  last_review                  4606 non-null   object
 20  review_scores_rating         4606 non-null   float64
 21  review_scores_accuracy       4585 non-null   float64
 22  review_scores_cleanliness    4585 non-null   float64
 23  review_scores_communication  4585 non-null   float64
 24  review_scores_location       4585 non-null   float64
 25  review_scores_value          4585 non-null   float64
 26  reviews_per_month            4606 non-null   float64
dtypes: float64(12), int64(5), object(10)
memory usage: 1.2+ MB

None

id                                0
host_since                        0
host_is_superhost                 0
neighbourhood                  2250
neighbourhood_cleansed            0
latitude                          0
longitude                         0
property_type                     0
room_type                         0
accommodates                      0
bathrooms                      5729
bedrooms                        382
beds                            109
price                             0
minimum_nights                    0
maximum_nights                    0
calendar_last_scraped             0
number_of_reviews                 0
first_review                   1123
last_review                    1123
review_scores_rating           1123
review_scores_accuracy         1144
review_scores_cleanliness      1144
review_scores_communication    1144
review_scores_location         1144
review_scores_value            1144
reviews_per_month              1123
dtype: int64

,id,latitude,longitude,accommodates,bathrooms,bedrooms,beds,minimum_nights,maximum_nights,number_of_reviews,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month
count,5.729000e+03,5729.000000,5729.000000,5729.000000,0.0,5347.000000,5620.000000,5729.000000,5729.000000,5729.000000,4606.000000,4585.000000,4585.000000,4585.000000,4585.000000,4585.000000,4606.000000
mean,8.188610e+16,37.351373,-121.974697,3.290103,NaN,1.619600,1.931317,13.176121,641.914645,34.460290,4.723139,4.798009,4.735138,4.830600,4.816840,4.690475,1.336198
std,2.064451e+17,0.073936,0.118236,2.418787,NaN,1.037482,1.502533,26.861549,494.059806,63.562509,0.544540,0.390754,0.450958,0.413634,0.347211,0.455451,1.566881
min,4.952000e+03,36.965600,-122.214140,0.000000,NaN,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.010000
25%,2.188225e+07,37.319546,-122.070110,2.000000,NaN,1.000000,1.000000,1.000000,90.000000,1.000000,4.680000,4.770000,4.670000,4.850000,4.790000,4.630000,0.290000
50%,3.977334e+07,37.355380,-121.962340,2.000000,NaN,1.000000,1.000000,3.000000,765.000000,9.000000,4.870000,4.920000,4.880000,4.960000,4.920000,4.800000,0.810000
75%,5.151011e+07,37.399790,-121.890230,4.000000,NaN,2.000000,2.000000,30.000000,1125.000000,39.000000,5.000000,5.000000,5.000000,5.000000,5.000000,4.940000,1.880000
max,6.494853e+17,37.480080,-121.380120,16.000000,NaN,9.000000,20.000000,600.000000,1125.000000,760.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,19.080000

In [14]:
abnb_df = pd.concat([abnb_sm_df, abnb_sc_df], axis = 0)

In [15]:
abnb_df = abnb_df.reset_index(drop=True)

In [16]:
df_main_features(abnb_df)

(9087, 27)

,id,host_since,host_is_superhost,neighbourhood,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bedrooms,beds,price,minimum_nights,maximum_nights,calendar_last_scraped,number_of_reviews,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month
0,4952,2009-01-24,t,"Palo Alto, California, United States",Unincorporated Areas,37.43932,-122.15741,Private room,Private room,1,NaN,1.0,1.0,$70.00,31,365,2022-06-16,76,2009-08-02,2022-04-02,4.79,4.81,4.88,4.83,4.89,4.78,0.48
1,21373,2009-01-24,t,"Palo Alto, California, United States",Unincorporated Areas,37.43972,-122.15532,Private room,Private room,1,NaN,1.0,1.0,$70.00,31,365,2022-06-16,264,2010-05-28,2022-05-15,4.87,4.82,4.79,4.90,4.96,4.74,1.80
2,26622,2010-04-24,f,"Daly City, California, United States",Daly City,37.69490,-122.47517,Private room in home,Private room,2,NaN,1.0,1.0,$150.00,3,7,2022-06-15,255,2010-07-02,2022-05-29,4.96,4.96,4.97,4.95,4.73,4.92,1.75
3,39342,2010-05-18,f,"Pacifica, California, United States",Pacifica,37.62972,-122.48739,Entire home,Entire home/apt,3,NaN,2.0,2.0,$138.00,31,365,2022-06-15,3,2010-08-22,2022-02-05,4.67,5.00,5.00,5.00,5.00,5.00,0.02
4,40560,2010-07-20,t,"Palo Alto, California, United States",Unincorporated Areas,37.45379,-122.13867,Private room in home,Private room,2,NaN,1.0,1.0,$115.00,2,100,2022-06-16,139,2010-09-18,2022-06-12,4.91,4.94,4.95,4.95,4.94,4.83,0.97

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9087 entries, 0 to 9086
Data columns (total 27 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           9087 non-null   int64
 1   host_since                   9087 non-null   object
 2   host_is_superhost            9087 non-null   object
 3   neighbourhood                5819 non-null   object
 4   neighbourhood_cleansed       9087 non-null   object
 5   latitude                     9087 non-null   float64
 6   longitude                    9087 non-null   float64
 7   property_type                9087 non-null   object
 8   room_type                    9087 non-null   object
 9   accommodates                 9087 non-null   int64
 10  bathrooms                    0 non-null      float64
 11  bedrooms                     8482 non-null   float64
 12  beds                         8924 non-null   float64
 13  price                        9087 non-null   object
 14  minimum_nights               9087 non-null   int64
 15  maximum_nights               9087 non-null   int64
 16  calendar_last_scraped        9087 non-null   object
 17  number_of_reviews            9087 non-null   int64
 18  first_review                 7461 non-null   object
 19  last_review                  7461 non-null   object
 20  review_scores_rating         7461 non-null   float64
 21  review_scores_accuracy       7434 non-null   float64
 22  review_scores_cleanliness    7434 non-null   float64
 23  review_scores_communication  7434 non-null   float64
 24  review_scores_location       7434 non-null   float64
 25  review_scores_value          7434 non-null   float64
 26  reviews_per_month            7461 non-null   float64
dtypes: float64(12), int64(5), object(10)
memory usage: 1.9+ MB

None

id                                0
host_since                        0
host_is_superhost                 0
neighbourhood                  3268
neighbourhood_cleansed            0
latitude                          0
longitude                         0
property_type                     0
room_type                         0
accommodates                      0
bathrooms                      9087
bedrooms                        605
beds                            163
price                             0
minimum_nights                    0
maximum_nights                    0
calendar_last_scraped             0
number_of_reviews                 0
first_review                   1626
last_review                    1626
review_scores_rating           1626
review_scores_accuracy         1653
review_scores_cleanliness      1653
review_scores_communication    1653
review_scores_location         1653
review_scores_value            1653
reviews_per_month              1626
dtype: int64

,id,latitude,longitude,accommodates,bathrooms,bedrooms,beds,minimum_nights,maximum_nights,number_of_reviews,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month
count,9.087000e+03,9087.000000,9087.000000,9087.000000,0.0,8482.000000,8924.000000,9087.000000,9087.000000,9087.000000,7461.000000,7434.000000,7434.000000,7434.000000,7434.000000,7434.00000,7461.000000
mean,7.829338e+16,37.429090,-122.106318,3.496313,NaN,1.682622,2.050314,12.488060,626.467701,41.916144,4.739725,4.810538,4.754580,4.844060,4.810858,4.70032,1.535620
std,2.025051e+17,0.133033,0.209554,2.647573,NaN,1.093528,1.677935,25.297504,507.363417,73.331347,0.503163,0.365210,0.422245,0.385695,0.333115,0.42155,1.717404
min,4.952000e+03,36.965600,-122.519040,0.000000,NaN,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.00000,0.010000
25%,2.146112e+07,37.338564,-122.254330,2.000000,NaN,1.000000,1.000000,1.000000,90.000000,2.000000,4.700000,4.780000,4.700000,4.860000,4.760000,4.64000,0.330000
50%,3.892668e+07,37.404240,-122.092110,2.000000,NaN,1.000000,1.000000,3.000000,365.000000,12.000000,4.880000,4.920000,4.890000,4.960000,4.900000,4.80000,0.950000
75%,5.139289e+07,37.482635,-121.936775,4.000000,NaN,2.000000,3.000000,28.000000,1125.000000,49.000000,5.000000,5.000000,5.000000,5.000000,5.000000,4.93000,2.150000
max,6.494853e+17,37.728360,-121.380120,16.000000,NaN,9.000000,27.000000,600.000000,10000.000000,885.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.00000,19.080000

In [17]:
abnb_df

,id,host_since,host_is_superhost,neighbourhood,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bedrooms,beds,price,minimum_nights,maximum_nights,calendar_last_scraped,number_of_reviews,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month
0,4952,2009-01-24,t,"Palo Alto, California, United States",Unincorporated Areas,37.43932,-122.15741,Private room,Private room,1,NaN,1.0,1.0,$70.00,31,365,2022-06-16,76,2009-08-02,2022-04-02,4.79,4.81,4.88,4.83,4.89,4.78,0.48
1,21373,2009-01-24,t,"Palo Alto, California, United States",Unincorporated Areas,37.43972,-122.15532,Private room,Private room,1,NaN,1.0,1.0,$70.00,31,365,2022-06-16,264,2010-05-28,2022-05-15,4.87,4.82,4.79,4.90,4.96,4.74,1.80
2,26622,2010-04-24,f,"Daly City, California, United States",Daly City,37.69490,-122.47517,Private room in home,Private room,2,NaN,1.0,1.0,$150.00,3,7,2022-06-15,255,2010-07-02,2022-05-29,4.96,4.96,4.97,4.95,4.73,4.92,1.75
3,39342,2010-05-18,f,"Pacifica, California, United States",Pacifica,37.62972,-122.48739,Entire home,Entire home/apt,3,NaN,2.0,2.0,$138.00,31,365,2022-06-15,3,2010-08-22,2022-02-05,4.67,5.00,5.00,5.00,5.00,5.00,0.02
4,40560,2010-07-20,t,"Palo Alto, California, United States",Unincorporated Areas,37.45379,-122.13867,Private room in home,Private room,2,NaN,1.0,1.0,$115.00,2,100,2022-06-16,139,2010-09-18,2022-06-12,4.91,4.94,4.95,4.95,4.94,4.83,0.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9082,48503190,2012-09-03,t,NaN,Palo Alto,37.45978,-122.14339,Entire guest suite,Entire home/apt,3,NaN,NaN,4.0,$100.00,2,28,2022-06-15,40,2021-06-23,2022-06-12,4.88,4.88,4.90,5.00,4.65,4.88,3.35
9083,35671852,2019-06-13,t,"East Palo Alto, California, United States",Palo Alto,37.45987,-122.12973,Entire home,Entire home/apt,3,NaN,NaN,2.0,$129.00,3,1125,2022-06-15,58,2019-06-22,2022-05-09,4.97,4.98,4.93,4.93,4.76,4.83,1.60
9084,32008649,2015-10-08,t,"East Palo Alto, California, United States",Palo Alto,37.45981,-122.14745,Entire home,Entire home/apt,4,NaN,2.0,2.0,$169.00,3,1125,2022-06-15,103,2019-02-13,2022-06-08,4.94,4.99,4.94,5.00,4.92,4.93,2.53
9085,31801684,2015-10-08,t,"Palo Alto, California, United States",Palo Alto,37.46018,-122.14418,Entire home,Entire home/apt,4,NaN,2.0,2.0,$169.00,3,1125,2022-06-15,88,2019-03-05,2022-06-09,4.84,4.92,4.92,4.98,4.85,4.86,2.20
9086,9062857,2014-09-30,t,"Menlo Park, California, United States",Palo Alto,37.45578,-122.15756,Entire home,Entire home/apt,6,NaN,3.0,3.0,$636.00,4,1125,2022-06-15,105,2015-11-05,2021-08-29,4.96,4.98,4.98,4.95,4.96,4.77,1.30

# Cleaning

In [18]:
def airbnb_cleaning(x):
    abnb_df = x
    

    # drop columns
    abnb_df = abnb_df.drop(columns=['bathrooms','property_type'], axis=1)
    
    
    # replace * in the column
    abnb_df['neighbourhood'] =abnb_df['neighbourhood'].str.replace(',.*', '')
    
    # fill na in the column
    abnb_df['neighbourhood'] = abnb_df['neighbourhood'].fillna(abnb_df['neighbourhood_cleansed'])
    
    
    # function ro replace characters in the column
    neigh_names = list(abnb_df['neighbourhood'].unique())
    neigh_names
    # neigh_names.remove(np.nan)
    neigh_names.remove('圣何塞')
    neigh_names.remove(' ')
    
    def neigh_sel(row):
        if row['neighbourhood'] in neigh_names:
            return row['neighbourhood']
        else:
            return row['neighbourhood_cleansed']
        return row['neighbourhood'] 
    
    abnb_df['neighbourhood'] = abnb_df.apply(neigh_sel, axis=1)
    
    # dropping the unneccessary column
    abnb_df = abnb_df.drop('neighbourhood_cleansed', axis=1)
    
    
    # fill the nans with mean of the columns
    cols_to_fill = ['bedrooms', 'beds', 'review_scores_rating', 'review_scores_accuracy', 'review_scores_cleanliness', 'review_scores_communication', 'review_scores_location', 'review_scores_value', 'reviews_per_month']
    for i in cols_to_fill:
        abnb_df[i].fillna(abnb_df[i].mean(), inplace=True)
    
    # number of reviews are zero in some rows so the other related columns should be 0
    num_rev_zeros = abnb_df[abnb_df['number_of_reviews']==0].index
    cols_to_edit = ['first_review','last_review', 'review_scores_rating', 'review_scores_accuracy', 'review_scores_cleanliness', 'review_scores_communication', 'review_scores_location', 'review_scores_value', 'reviews_per_month']
    abnb_df.loc[num_rev_zeros, cols_to_edit] = 0
    
    # changing the dollar sign
    abnb_df.price = abnb_df.price.str.replace('$','')
    abnb_df.price = pd.to_numeric(abnb_df.price, errors='coerce')
    
    
    # datetime conversion
    abnb_df['host_since']=pd.to_datetime(abnb_df['host_since'])
    abnb_df['calendar_last_scraped']=pd.to_datetime(abnb_df['calendar_last_scraped'])
    abnb_df['first_review']=pd.to_datetime(abnb_df['first_review'])
    abnb_df['last_review']=pd.to_datetime(abnb_df['last_review'])
    
        
    # transforming accommodates column
    accommodates_labels = ['Single', 'Couple', 'Small groups', 'Medium groups', 'Large Groups']
    abnb_df['accommodates_def'] = pd.cut(abnb_df['accommodates'],[0,1,2,6,12,17],labels=accommodates_labels)
    abnb_df[['accommodates','accommodates_def']].head(20)
    abnb_df['accommodates'] = abnb_df['accommodates_def']
        
        
    # airbnb hotel room     
    abnb_df = abnb_df[~abnb_df.room_type.str.contains("Hotel room")]   
    
    
    
    # counties
    count_counties = abnb_df.neighbourhood.value_counts(dropna=False)
    less_counties = list(count_counties[count_counties < 50].index)
    abnb_df['neighbourhood'] = np.where(abnb_df['neighbourhood'].isin(less_counties),'other', abnb_df['neighbourhood'])
    
    
    # dropped more cols
    abnb_df = abnb_df.drop(columns = ['calendar_last_scraped', 'first_review', 'last_review'],axis=1)
        
        
        
    # extracting the year    
    abnb_df['host_since'] = pd.DatetimeIndex(abnb_df['host_since']).year
    
    
    # host_since labelling
    host_since_labels = ['2009-2012', '2013-2016', '2017-2020', '2021-2022']
    abnb_df['host_since_def'] = pd.cut(abnb_df['host_since'],[2008,2012,2016,2020,2022],labels=host_since_labels)
    abnb_df['host_since'] = abnb_df['host_since_def']
    
    
    
    # dropping cols that was created
    abnb_df=abnb_df.drop(columns = ['accommodates_def','host_since_def'], axis=1)

    return abnb_df

In [19]:
listing_cleaned = airbnb_cleaning(abnb_df)

In [20]:
listing_cleaned

,id,host_since,host_is_superhost,neighbourhood,latitude,longitude,room_type,accommodates,bedrooms,beds,price,minimum_nights,maximum_nights,number_of_reviews,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month
0,4952,2009-2012,t,Palo Alto,37.43932,-122.15741,Private room,Single,1.000000,1.0,70.0,31,365,76,4.79,4.81,4.88,4.83,4.89,4.78,0.48
1,21373,2009-2012,t,Palo Alto,37.43972,-122.15532,Private room,Single,1.000000,1.0,70.0,31,365,264,4.87,4.82,4.79,4.90,4.96,4.74,1.80
2,26622,2009-2012,f,Daly City,37.69490,-122.47517,Private room,Couple,1.000000,1.0,150.0,3,7,255,4.96,4.96,4.97,4.95,4.73,4.92,1.75
3,39342,2009-2012,f,Pacifica,37.62972,-122.48739,Entire home/apt,Small groups,2.000000,2.0,138.0,31,365,3,4.67,5.00,5.00,5.00,5.00,5.00,0.02
4,40560,2009-2012,t,Palo Alto,37.45379,-122.13867,Private room,Couple,1.000000,1.0,115.0,2,100,139,4.91,4.94,4.95,4.95,4.94,4.83,0.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9082,48503190,2009-2012,t,Palo Alto,37.45978,-122.14339,Entire home/apt,Small groups,1.682622,4.0,100.0,2,28,40,4.88,4.88,4.90,5.00,4.65,4.88,3.35
9083,35671852,2017-2020,t,East Palo Alto,37.45987,-122.12973,Entire home/apt,Small groups,1.682622,2.0,129.0,3,1125,58,4.97,4.98,4.93,4.93,4.76,4.83,1.60
9084,32008649,2013-2016,t,East Palo Alto,37.45981,-122.14745,Entire home/apt,Small groups,2.000000,2.0,169.0,3,1125,103,4.94,4.99,4.94,5.00,4.92,4.93,2.53
9085,31801684,2013-2016,t,Palo Alto,37.46018,-122.14418,Entire home/apt,Small groups,2.000000,2.0,169.0,3,1125,88,4.84,4.92,4.92,4.98,4.85,4.86,2.20
9086,9062857,2013-2016,t,Menlo Park,37.45578,-122.15756,Entire home/apt,Small groups,3.000000,3.0,636.0,4,1125,105,4.96,4.98,4.98,4.95,4.96,4.77,1.30

In [22]:
listing_cleaned.to_csv("/Users/begumerdem/IH-Labs/WEEK_5_Lab/archive/abnb_listings_cleaned.csv", index = False)

In [23]:
import pymysql
from sqlalchemy import create_engine

from getpass import getpass  # To get the password without showing the input

In [24]:
password = getpass()

········

In [25]:
connection_string = 'mysql+pymysql://root:'+password+'@localhost/airbnb'
engine = create_engine(connection_string)

In [27]:
listing_cleaned.to_sql('listings', engine, if_exists='replace', index = False)

9085

In [ ]:
categorical_df = abnb_df.select_dtypes(object)
categorical_df

In [ ]:
numerical_df = abnb_df.select_dtypes(exclude='object')
numerical_df

In [ ]:
# Defining a function that differentiates between continuous and discrete variables

def differ_cont_disc(df):
    
    df_continuous = pd.DataFrame()
    df_discrete = pd.DataFrame()
    
    for name in df.columns:
        if df[name].nunique() >50:
            df_continuous[name] = df[name]
        else:
            df_discrete[name] = df[name]
    return df_continuous, df_discrete


continuous_df, discrete_df = differ_cont_disc(numerical_df)

In [ ]:
continuous_df

In [ ]:
discrete_df

In [ ]:
# Plotting a correlation matrix

In [ ]:
correlations = continuous_df.corr()
correlations

In [ ]:
correlations = abnb_df.corr()
correlations

In [ ]:
# Plotting a correlation matrix to see what's happening with numerical values

fig, ax=plt.subplots(figsize=(10,8))
correlations_matrix = continuous_df.corr()
sns.heatmap(correlations_matrix, annot=True)
plt.show()

In [ ]:
# after seeing the heat map I've decided to keep only review_scores_rating 
# and reviews per month columns from all other columns for the review feature.
# since there is a very high correlatio among review columns

In [ ]:
abnb_df = abnb_df.drop(['review_scores_accuracy','review_scores_cleanliness','review_scores_communication', 'review_scores_location', 'review_scores_value'], axis=1)

In [ ]:
abnb_df

In [ ]:
# plotting variable types

In [ ]:
def plot_cont_displot(df):
    for name in df.columns:
        sns.displot(data=df, x=name, kde=True)
    return

plot_cont_displot(discrete_df)

In [ ]:
def plot_cont_displot(df):
    for name in df.columns:
        sns.displot(data=df, x=name, kde=True)
    return

plot_cont_displot(continuous_df)

In [ ]:
# outliers in continuous variables

In [ ]:
def outliers_cont(df):
    for name in df.columns:
        sns.boxplot(data=df, x=name)
        plt.show()
    
outliers_cont(continuous_df)

In [ ]:
def detect_outlier(column):
    # find q1 and q3 values
    q1, q3 = np.percentile(sorted(column), [25, 75])
 
    # compute IQR
    iqr = q3 - q1
 
    # find lower and upper bounds
    lower_bound = q1 - (1.5 * iqr)
    upper_bound = q3 + (1.5 * iqr)
 
    outliers = [x for x in column if x <= lower_bound or x >= upper_bound]
 
    return outliers

In [ ]:
# input data
rsr_outliers = detect_outlier(continuous_df['review_scores_rating'])
rpm_outliers = detect_outlier(continuous_df['reviews_per_month'])
mn_outliers = detect_outlier(continuous_df['minimum_nights'])

In [ ]:
display(len(rsr_outliers))
display(len(rpm_outliers))
display(len(mn_outliers))

In [ ]:
abnb_df.describe()

In [ ]:
# about the high number of outliers, I don't think that is not reasonable.
# some properties got so many reviews while some of them didn't get any
# likewise some properties

In [ ]:
# abnb_df.loc[:, 'accommodates':'beds'].apply(np.argmax, axis =0)

In [ ]:
# abnb_df.loc[633:639, 'accommodates':'beds']

In [ ]:
# abnb_df.loc[420:426, 'accommodates':'beds']

In [ ]:
# abnb_df.loc[7565:7575, 'accommodates':'beds']

In [ ]:
# I also checked the airbnb pages or that houses to see 
# whether the numbers are accurate and they are accurate 
# so I'm not dropping the outliers

In [ ]:
abnb_df

In [ ]:
abnb_df.nunique()

In [ ]:
numerical_df.nunique()

In [ ]:
continuous_df.nunique()

In [ ]:
discrete_df.nunique()

In [ ]:
categorical_df.nunique()

In [ ]:
categorical_df = pd.concat([discrete_df, categorical_df], axis = 1)
categorical_df = categorical_df.reset_index(drop=True)

In [ ]:
categorical_df

In [ ]:
numerical_df = continuous_df

In [ ]:
numerical_df

In [ ]:
# Finally: Looking at numerical and categorical variables one last time

In [ ]:
# Looking at Categorical features

def cntplot_cat(df):
    for column in df.columns:
        sns.countplot(x=df[column])
        plt.show()
    return None
   

cntplot_cat(categorical_df)

In [ ]:
# just realized the datatype of price is wrong so need to change and rerun datatypes

In [ ]:
abnb_df.price

In [ ]:
def cntplot_cat(df):
    for column in df.columns:
        sns.countplot(x=df[column])
        plt.show()
    return None
   

cntplot_cat(categorical_df)

In [ ]:
abnb_df.info()

In [ ]:
abnb_df

In [ ]:
abnb_df.neighbourhood.nunique()

In [ ]:
abnb_df.to_csv("/Users/begumerdem/IH-Labs/WEEK_5_Lab/archive/cleaned_airbnb_01.csv")

# If you just use file name then it will save CSV file in working directory.
# Example path : C:/Users/<>/Desktop/<file name>.csv